version: '3'

services:
  web:
    build: .
    #volumes:
    #    - "${CONTAINERDATA}/${PROJECT_NAME}/data:/home/data"
    ports:
      - "80:80"
    links:
      - mysql
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6.23
    #volumes:
    #    - "${CONTAINERDATA}/${PROJECT_NAME}/mysql:/var/lib/mysql"
    #    - "${CONTAINERDATA}/${PROJECT_NAME}/data:/home/data"
    env_file:
      - .env
